"""Question bank for the Streamlit interview app."""

QUESTION_BANK = {
    "Technical": {
        "Easy": [
            "Can you explain the difference between a list and a tuple in Python?",
            "What is the purpose of version control tools like Git?",
            "How does a REST API differ from a regular web page?",
            "What is the difference between frontend and backend development?",
            "Why is testing important in software development?",
            "What does a database index do?",
            "What is the difference between HTTP and HTTPS?",
            "When would you use a dictionary instead of a list?",
            "What is a bug, and how do you usually debug one?",
            "What are environment variables used for?",
        ],
        "Medium": [
            "How would you design error handling for a production API?",
            "What trade-offs do you consider when choosing SQL vs NoSQL?",
            "How do caching layers improve application performance?",
            "Explain the difference between authentication and authorization.",
            "How would you structure a Python project for maintainability?",
            "What metrics would you monitor for a backend service?",
            "How do you approach refactoring legacy code safely?",
            "When would you choose asynchronous processing over synchronous?",
            "How do unit tests and integration tests complement each other?",
            "Describe how you would secure sensitive user data at rest and in transit.",
        ],
        "Hard": [
            "Design a rate-limiting strategy for a high-traffic public API.",
            "How would you diagnose intermittent latency spikes in production?",
            "What consistency model would you choose for a global distributed system and why?",
            "How would you design an idempotent payment processing endpoint?",
            "Describe a strategy for zero-downtime database migrations.",
            "How would you isolate and recover from cascading failures in microservices?",
            "What are the trade-offs between event-driven and request-response architectures?",
            "How would you plan capacity for a service with unpredictable traffic?",
            "How would you design observability for an ML-powered recommendation system?",
            "What security risks are most critical in multi-tenant SaaS platforms?",
        ],
    },
    "Behavioral": {
        "Easy": [
            "Tell me about yourself and your background.",
            "Why are you interested in this role?",
            "Describe a time you worked well in a team.",
            "How do you prioritize your daily tasks?",
            "How do you handle feedback from peers or managers?",
            "Tell me about a recent accomplishment you're proud of.",
            "How do you manage deadlines when multiple tasks compete?",
            "Describe your preferred communication style at work.",
            "How do you stay motivated during repetitive tasks?",
            "What type of work environment helps you do your best work?",
        ],
        "Medium": [
            "Describe a time you had a conflict with a teammate and how you resolved it.",
            "Tell me about a project where priorities changed unexpectedly.",
            "How have you handled making a mistake at work?",
            "Describe a time you influenced a decision without formal authority.",
            "Tell me about a time you had to learn a new skill quickly.",
            "How do you handle ambiguity when expectations are unclear?",
            "Describe a time you had to balance speed and quality.",
            "Tell me about a time you gave difficult feedback to someone.",
            "How do you approach cross-functional collaboration?",
            "Describe a situation where you improved a team process.",
        ],
        "Hard": [
            "Tell me about a time you failed and what changed afterward.",
            "Describe a high-stakes decision you made with limited information.",
            "How do you respond when leadership disagrees with your recommendation?",
            "Tell me about a time you had to rebuild trust after a setback.",
            "Describe a time you led through significant organizational change.",
            "How do you handle persistent underperformance on your team?",
            "Tell me about a time you advocated for an unpopular but necessary decision.",
            "Describe a time competing stakeholders pulled you in different directions.",
            "How have you mentored someone through a difficult challenge?",
            "Tell me about a decision that had long-term impact on your team.",
        ],
    },
    "System Design": {
        "Easy": [
            "How would you design a basic URL shortener?",
            "What core components are needed for a chat application?",
            "How would you design a simple file upload service?",
            "What would you store in a cache for an e-commerce homepage?",
            "How would you design user profile storage for a social app?",
            "How would you support search for products in an online store?",
            "What are the basic pieces of a notification system?",
            "How would you design a simple logging pipeline?",
            "How would you design an API gateway for multiple services?",
            "What are key design considerations for a to-do app backend?",
        ],
        "Medium": [
            "Design a scalable real-time chat system for millions of users.",
            "How would you design a recommendation feed with low latency?",
            "Design a document collaboration platform with version history.",
            "How would you design a video upload and streaming workflow?",
            "Design a metrics aggregation system for microservices.",
            "How would you design a global notification delivery system?",
            "Design a service to detect and prevent duplicate transactions.",
            "How would you architect a feature flag platform?",
            "Design a calendar scheduling system with conflict handling.",
            "How would you design a full-text search service for large datasets?",
        ],
        "Hard": [
            "Design a globally distributed social feed with strong reliability.",
            "How would you design a fraud detection pipeline with real-time decisions?",
            "Design a multi-region order processing platform with disaster recovery.",
            "How would you design a highly available pub/sub system?",
            "Design a low-latency analytics platform for streaming events.",
            "How would you design data retention and archival for petabyte scale logs?",
            "Design an architecture for serving ML models with online feature computation.",
            "How would you design a payment platform that supports retries and reconciliation?",
            "Design a resilient workflow orchestration engine for long-running jobs.",
            "How would you design tenant isolation in a large multi-tenant SaaS product?",
        ],
    },
    "Case Study": {
        "Easy": [
            "A feature adoption is low after launch. How would you investigate?",
            "Your app ratings dropped this week. What first steps would you take?",
            "How would you assess whether a new feature should be built?",
            "A process takes too long. How would you identify bottlenecks?",
            "How would you prioritize bug fixes vs new features for a small team?",
            "A stakeholder asks for urgent changes. How do you respond?",
            "How would you measure success for a new onboarding flow?",
            "A teammate disagrees with your plan. How would you align?",
            "How would you prepare for a project kickoff with unclear requirements?",
            "How do you structure a problem statement before proposing solutions?",
        ],
        "Medium": [
            "A key funnel step has a 20% drop. How would you diagnose and fix it?",
            "Customer churn increased over two quarters. How would you respond?",
            "You have one sprint to improve reliability. What would you prioritize?",
            "A product launch missed targets. How would you run a postmortem?",
            "How would you evaluate build vs buy for a core internal tool?",
            "A competitor released a similar product. What is your response plan?",
            "How would you allocate limited engineering capacity across competing initiatives?",
            "A dashboard shows conflicting metrics. How would you reconcile them?",
            "How would you recover momentum for a delayed cross-team project?",
            "How would you structure experiments to validate a pricing change?",
        ],
        "Hard": [
            "Revenue is down and budgets are frozen. How would you reset the roadmap?",
            "A critical outage impacted enterprise clients. Outline your recovery strategy.",
            "How would you handle a high-profile security incident response?",
            "Two strategic initiatives conflict at the executive level. How do you proceed?",
            "How would you redesign an underperforming product line within 90 days?",
            "Regulatory changes require major architecture updates. What's your plan?",
            "How would you manage communication during a prolonged service degradation?",
            "A major partnership failed unexpectedly. How would you mitigate impact?",
            "How would you restore trust after repeated delivery misses?",
            "Your team must cut costs by 30% without harming core UX. What do you do?",
        ],
    },
}


def get_questions(interview_type: str, difficulty: str) -> list[str]:
    """Return questions by interview type and difficulty with safe fallbacks."""
    type_questions = QUESTION_BANK.get(interview_type, QUESTION_BANK["Technical"])
    return type_questions.get(difficulty, type_questions["Medium"])
